### PR TITLE
Extracted vital values to variables

### PR DESCRIPTION
**Pull request by Virrum**
When looking at the variables and the code, do you understand what the different variables are ment for?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1127747245019971)

### CODE REVIEW

**Comment by pavsaund** [comment]
I like the naming convention. It's easy to understand the connection between the variables and their usage. 

What I'm not so sure of is if we need all of these variables. Certain variables only have a one or two specific values. Anything else breaks the design and you'd need to override the entire class. Perhaps those styles could be exposed as behaviours? 

Example of something that can easily break: `$navigation-view-position` 
Examples of some good variables: `$navigation-view-item-toggle-expand-after-height`, `$navigation-view-item-toggle-expand-after-width`, `$navigation-view-item-toggle-expand-after-margin-left`

Perhaps an approach where we expose variables for spacing / colors / fonts. For completely different look & feel you'd need to override everything or we could introduce new component behaviours with different classes?

Thoughts?

**Comment by Virrum** [comment]
I do agree! I'll find a razor (must **not** be confused with the markup/view language for ASP.NET MVC) and revert some of the variables.

**Comment by Virrum** [comment]
Better now @pavsaund ?

**Review by einari — APPROVED** [review]
Looking good. Agree with @pavsaund on exposing some things as behaviors/attributes on the control itself. I think we'll find a rule of thumb after a while in what goes where. 
You good with things @pavsaund and we can pull this in??

**Review by pavsaund — APPROVED** [review]
@einari @Virrum: I dropped the ball on this - this is good - approving!

**Comment by pavsaund** [comment]
oops I merged it in - is that OK @einari?

**Pull request merged**
